name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: sha-${{ github.sha }}

    steps:
      - uses: actions/checkout@v3

      # 1. Secret Scan toàn repo
      - name: Gitleaks
        uses: zricethezav/gitleaks-action@v2

      # 2. Docker login
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. Build & Push frontend
      - name: Build & push frontend
        run: |
          docker build -t chywiz/frontend:${IMAGE_TAG} ./frontend
          docker push chywiz/frontend:${IMAGE_TAG}
       # 3.5. Update image tag trong deploy/frontend/deploy.yaml
      - name: Update image tag in frontend deployment YAML
        run: |
          sed -i "s|chywiz/frontend:.*|chywiz/frontend:${IMAGE_TAG}|g" deploy/frontend/deployment.yaml

      - name: Commit & push updated image tag
        env:
          PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "CI Bot"
          git config user.email "ci@chywiz.com"
          git add deploy/frontend/deploy.yaml
          git commit -m "Update frontend image to ${IMAGE_TAG}" || echo "No changes"
          git push https://x-access-token:${PAT}@github.com/${{ github.repository }}.git HEAD:main


      # 4. Build & Push auth-service
      - name: Build & push auth-service
        run: |
          docker build -t chywiz/auth-service:${IMAGE_TAG} ./backend/auth-service
          docker push chywiz/auth-service:${IMAGE_TAG}

      # 5. Build & Push budget-service
      - name: Build & push budget-service
        run: |
          docker build -t chywiz/budget-service:${IMAGE_TAG} ./backend/budget-service
          docker push chywiz/budget-service:${IMAGE_TAG}
          
      # 6. Build & Push transaction-service
      - name: Build & push transaction-service
        run: |
          docker build -t chywiz/transaction-service:${IMAGE_TAG} ./backend/transaction-service
          docker push chywiz/transaction-service:${IMAGE_TAG}

      # 7. Scan image bằng Trivy (VD: auth-service)
      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: chywiz/auth-service:${{ env.IMAGE_TAG }}
     
