name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    # env:
    #   IMAGE_TAG: sha-${{ github.sha }}

    steps:
      - uses: actions/checkout@v3

      # 1. Secret Scan toàn repo
      - name: Gitleaks
        uses: zricethezav/gitleaks-action@v2

      # 2. Docker login
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. Build & Push frontend
      - name: Build & push frontend
        run: |
          docker build -t chywiz/frontend:latest ./frontend
          docker push chywiz/frontend:latest
      # 4. Build & Push auth-service
      - name: Build & push auth-service
        run: |
          docker build -t chywiz/auth-service:latest ./backend/auth-service
          docker push chywiz/auth-service:latest

      # 5. Build & Push budget-service
      - name: Build & push budget-service
        run: |
          docker build -t chywiz/budget-service:$latest ./backend/budget-service
          docker push chywiz/budget-service:latest
          
      # 6. Build & Push transaction-service
      - name: Build & push transaction-service
        run: |
          docker build -t chywiz/transaction-service:$latest ./backend/transaction-service
          docker push chywiz/transaction-service:latest

      # 7. Scan image bằng Trivy (VD: auth-service)
      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: chywiz/auth-service:latest
     
